import React from 'react'
import Title from '../layouts/Title'
import ProjectCard from './ProjectCard';
import { clothingimg, portfolioimg, projectOne, projectTwo, voicebotimg, whatnext, whatnextimg } from '../../assets';
const Projects = () => {
  return (
    <section
      id="projects"
      className="w-full py-20 border-b-[1px] border-b-black"
    >
      <div className="flex justify-center items-center text-center">
        <Title title="VISIT MY PROJECTS" des="My Projects" />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6 xl:gap-12">
        <ProjectCard
          title="Food App"
          des="Created a mobile app for managing the waste food generated by the Catering
          Services/Restaurants creating a portal for easy donation to the needy people.
          Languages used were Kotlin, Sql and also integrated payment portal using Razorpay"
          src={projectOne}
          gitlink={"https://github.com/Parth-Gala/The_Free_Food_Network"}
        />
        <ProjectCard
          title="Arduino Codes"
          des="Basic Codes of Arduino(AtMega/UNO) for interfacing with sensors using various communication methods also integrated the robots 3 & 4 wheel holonomic drive with I.P live feed and PS5 Bluetooth.  Implemented P.I.D. control for optimal drive performance"
          src={projectTwo}
          gitlink={"https://github.com/Parth-Gala/Arduino-Codes"}
          
        />
        <ProjectCard
          title="Clothing Store Website"
          des="Designed an aesthetic responsive clothing website by seamlessly integrating backend and frontend, featuring captivating login and signup pages along with a classmate"
          src={clothingimg}
          gitlink={"https://github.com/harsh-sss/e_commerce.github.io"}
          hostlink={"https://harsh-sss.github.io/e_commerce.github.io/"}

        />
        <ProjectCard
          title="Param(Voice-Assistant TalkBot)"
          des="Developed a voice assistant bot in Python that can respond to user queries. It utilizes an API to retrieve news and read them aloud. Additionally, the bot is capable of sending emails, playing songs, and setting alarms and timers."
          src={voicebotimg}
          gitlink={"https://github.com/Parth-Gala/Voice-Assistant-"}
        />
        <ProjectCard
          title="Portfolio Website"
          des="Created a personal portfolio website in Reactjs as a part of learning and creativity"
          src={portfolioimg}
          gitlink={"https://github.com/Parth-Gala/parth-portfolio"}
          hostlink={"https://parth-gala.github.io/parth-portfolio/"}
        />
        <ProjectCard
          title="Upcoming Next"
          des="Wait for more such projects"
          src={whatnextimg}
        />
       
      </div>
    </section>
  );
}

export default Projects
